name: Prepare release with a Pull request
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
jobs:
  prepare-release:
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Get release version
      - name: Get release version from pubspec
        run: ::set-output name=RELEASE_VERSION::$(echo $(cat pubspec.yaml) | sed -ne 's/[^0-9]*\(\([0-9]\.\)\{0,4\}[0-9][^.]\).*/\1/p')
        shell: bash
        id: release-version
    # Create release branch from release version
      - name: Create branch release/${{steps.release-version.outputs.RELEASE_VERSION}}
        run: git switch -c release//${{steps.release-version.outputs.RELEASE_VERSION}} && git push -u origin release//${{steps.release-version.outputs.RELEASE_VERSION}}        
      - name: checkout on release branch  
        uses: actions/checkout@release/${{steps.release-version.outputs.RELEASE_VERSION}}
        # Checkout
      - name: Checkout on the brnch
        uses: actions/checkout@v2
