name: Prepare release with a Pull request
on: 
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Get release version
      - name: Get release version from pubspec
        run: echo '::set-output name=RELEASE_VERSION::$(echo $(cat pubspec.yaml) | sed -ne \'s/[^0-9]*\(\([0-9]\.\)\{0,4\}[0-9][^.]\).*/\1/p\')'
        shell: bash
        id: release-version