name: Prepare release with a Pull request
on: 
  workflow_dispatch:

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Get latest published release tag
        id: get_latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
      - name: Generate changelog since last published release
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          future_release: ${{ github.ref }}
          since_tag: ${{ steps.get_latest_release.outputs.release }}
      - name: Upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md
  draft-release:
    name: Draft Github release
    needs: generate-changelog
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Download changelog
      uses: actions/download-artifact@v2
      with:
        name: changelog
    - name: Draft release with changelog
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: CHANGELOG.md
        draft: true
        prerelease: false
  # prepare-release:
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     # Checkout
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: "0"
  #     # Get release version
  #     - name: Get version to release
  #       uses: mikefarah/yq@master
  #       id: release-version
  #       with:
  #         cmd: "yq e '.version' pubspec.yaml"
  #     - name: 'Get Previous tag'
  #       id: previoustag
  #       uses: "WyriHaximus/github-action-get-previous-tag@v1"
  #       with:
  #         fallback: $(git rev-list --max-parents=0 HEAD) # Initial commit if no tag found
  #     - name: Create commits
  #       run: |
  #         git config user.name 'Bernard Release Bot'
  #         git config user.email 'tmarmillot@users.noreply.github.com'
  #         cp CHANGELOG.md  changelog.tmp
  #         echo "# ${{steps.release-version.outputs.result}}" > CHANGELOG.md
  #         git log --pretty="- %s" HEAD...${{ steps.previoustag.outputs.tag }} HEAD >> CHANGELOG.md
  #         cat changelog.tmp >> CHANGELOG.md
  #         rm -rf changelog.tmp
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v3
  #       id: cpr
  #       with:
  #         branch: release/${{steps.release-version.outputs.result}}
  #         title: '[Release] welcome ${{steps.release-version.outputs.result}}'
  #         commit-message: "welcome ${{steps.release-version.outputs.result}} :bookmark:"
  #         committer: GitHub <noreply@github.com>
  #         author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
  #         delete-branch: true
  #         labels: release
  #         body: "Don't forget to check the changelog :rocket:"