name: Prepare release with a Pull request
on: 
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Get release version
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: echo "::set-output name=RELEASE_VERSION::$(yq e '.version' pubspec.yaml)' 
          shell: bash
          id: release-version
    # Create release branch from release version
      - name: Create branch release/${{steps.release-version.outputs.RELEASE_VERSION}}
        run: 'git switch -c release//${{steps.release-version.outputs.RELEASE_VERSION}} && git push -u origin release//${{steps.release-version.outputs.RELEASE_VERSION}}'
