name: Prepare release with a Pull request
on: 
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Get release version
      - name: Get version to release
        uses: mikefarah/yq@master
        id: release-version
        with:
          cmd: "yq e '.version' pubspec.yaml"
      
      - name: Create commits
        run: |
          git config user.name 'Bernard Release Bot'
          git config user.email 'tmarmillot@users.noreply.github.com'
          cp CHANGELOG.md  changelog.tmp
          echo "# ${{steps.release-version.outputs.result}}" > CHANGELOG.md
          git log --pretty="- %s" >> CHANGELOG.md
          cat changelog.tmp >> CHANGELOG.md
          rm -rf changelog.tmp
          git add -A
          git commit -m "welcome ${{steps.release-version.outputs.result}} :bookmark:"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/${{steps.release-version.outputs.result}}
          title: '[Release] welcome ${{steps.release-version.outputs.result}} :bookmark:'
          delete-branch: true