name: test

on:
  pull_request_target:
    branches:
      - main
    types: [labeled,closed]

jobs:

  release:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          # Get release version
      - name: Get version to release
        uses: mikefarah/yq@master
        id: release-version
        with:
          cmd: "yq e '.version' pubspec.yaml"
      - name: Bump version and push tag
        id: next_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          custom_tag: ${{steps.release-version.outputs.result}}
      - name: Draft release with changelog
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false   
