name: test

on:
  pull_request_target:
    branches:
      - main
    types: [labeled,closed]

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          # Get release version
    - name: debug 
      run: ${{contains(github.event.pull_request.labels.*.name, 'release')}}
    - name: Get version to release
      uses: mikefarah/yq@master
      id: release-version
      with:
        cmd: "yq e '.version' pubspec.yaml"
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{steps.release-version.outputs.result}}
        tag_prefix: ""
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: "Welcome the new release"
    - name: prepare for next development iteration
      uses: mikefarah/yq@master
      id: development-version
      with:
        cmd: "yq  eval --null-input '.version = ${{ steps.tag_version.outputs.new_version }}'  pubspec.yaml"
    - name: commit & push next version
      uses: EndBug/add-and-commit@v7
      with:
        message: 'prepare for next development iteration'