name: test

on:
  pull_request_target:
    branches:
      - main
    types: [labeled,closed]

jobs:
  tagging:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          # Get release version
    - name: debug 
      run: ${{ github.event.label.name == 'label_name' }}
    - name: Get version to release
      uses: mikefarah/yq@master
      id: release-version
      with:
        cmd: "yq e '.version' pubspec.yaml"
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{steps.release-version.outputs.result}}